main2:
	gcc -O2 -c jh.c -o jh2.o
	gcc -O2 -c main.c -o main2.o
	gcc main2.o jh2.o -o main2
main3:
	gcc -O3 -c jh.c -o jh3.o
	gcc -O3 -c main.c -o main3.o
	gcc main3.o jh3.o -o main3
clean:
	rm -f main2 main3  *.o
